### ISSUE TITLE
Error during import model what's name contains space

### ISSUE THREAD

**Issue by Dgzt** [JamesTKhan/Mundus#107]
**Describe the bug**
Mundus editor don't find the texture if it's name contains space.

**To Reproduce**
1. Create a texture for a model in Blender what's name contains space.
2. Go to Mundus editor
2. Click on 'Import/Import 3D model' button
3. Select the model
4. Click to 'IMPORT' button.
5. See error

**Screenshots**
![blender](https://user-images.githubusercontent.com/1684274/196046881-b2d1c925-95ec-471a-b3cb-7ab5a25c8cff.png)
![mundus_editor](https://user-images.githubusercontent.com/1684274/196046883-e80d144e-5a9e-4437-9a4b-41f91bce7366.png)

**Comment by Dgzt** [comment]
Should we change all "%20" text to " " in file name?

**Comment by JamesTKhan** [comment]
I don't think we can do anything to fix this from the Mundus side. The error appears to come from within gdx-gltf GLTFLoader process. I replicated the same issue on a non-Mundus project using gdx-gltf.

**Comment by Dgzt** [comment]
I've opened an issue on gdx-gltf project: https://github.com/mgsx-dev/gdx-gltf/issues/81

**Comment by Dgzt** [comment]
mgsx-dev fixed this issue in gdx-gltf project. Should we wait for the next gdx-gltf release or use master-SNAPSHOT version?

**Comment by JamesTKhan** [comment]
After chat with MGSX is discord they intend to release a new gdx-gltf version soon. Once that is released we can update to that, or we could point to a specific commit id now. I would rather not point to master-SNAPSHOT as that is changing often and we want to have consistent versioning and control when we update the library on the Mundus side. 

If the release is not out by end of next week we could move forward with an upgrade to point to a specific commit id so will follow up next week on this.

**Comment by Dgzt** [comment]
I tried with 2.1.0 version of gdx-gltf. This version doesn't solve this issue because we doesn't use SeparatedDataFileResolver file (source: https://github.com/mgsx-dev/gdx-gltf/commit/7b6253dc93b3fa7e6b71ea07dd5ac4a457f655c5). I think we should copy this decodePath(String) method to FileHandleWithDependencies and use it like:

```
dto.images?.forEach {
            val depFile = FileHandle(file.parent().path() + '/' + decodePath(it.uri))
            if (depFile.exists()) {
                images.add(depFile)
                dependencies.add(depFile)
            }
        }
```

**Comment by JamesTKhan** [comment]
I will take another look, but when I replicated this the other day, the stack trace pointed to SeparatedDataFileResolver

**Comment by JamesTKhan** [comment]
Yes your suggestion above appears to resolve the issue. Do you want to implement it or should I go ahead?

**Comment by Dgzt** [comment]
I reverted the changes on my environment, if you have this changes on your environment pls go head.

**Comment by JamesTKhan** [comment]
PR opened
