### ISSUE TITLE
New scene method creates file(s) but doesn't save project

### ISSUE THREAD

**Issue by Dgzt** [JamesTKhan/Mundus#115]
**Describe the bug**
If we create a new scene then the application creates scene file(s) in the project directory but doesn't save the project. And if we close the Mundus editor without project saving and reopen it then the new scene is missing but it's file is still in project directory. 

**To Reproduce**
1. Click on 'Scenes' / Add scene" button
2. Add new scene
3. Close Mundus editor without project saving
4. Open Mundus editor
5. Click on "Scenes" menu
6. The new scene is missing

**Comment by Dgzt** [comment]
@JamesTKhan Should we save project if we add new scene?

**Comment by JamesTKhan** [comment]
That seems like the best approach to me.
