### ISSUE TITLE
ability to add meta data to GameObjects 

### ISSUE THREAD

**Issue by antzGames** [JamesTKhan/Mundus#150]
**Is your feature request related to a problem? Please describe.**
As a game developer I want Mundus editor to add a new Meta Data Component type for GameObjects so that I can store physics parameters or any other meta data parameters to be used in the runtime.

**Describe the solution you'd like**
I know long term plans are to integrate a physics engine in Mundus.  Also there are many physics engines available.  Initially having a simple _Meta Data Component_ type available to GameObjects that will allow you to store **one JSON entry** and make it available in the runtime.  

This Meta Data Component type can be useful not just for storing physics parameters but ANY parameters.  Hopefully it will be reusable/useful when and if Mundus is integrated with a physics library.

**Additional context**

So I was thinking in the editor, if you select `Add Component` you currently get a panel asking what type of component you want to add.  The drop down will allow a new component type META Data Component.  This component has one data field in which you can store any String (i.e. JSON Text or XML or YAML).    

![image](https://user-images.githubusercontent.com/10563814/233088378-26f7b79a-5333-40d4-8547-7c8da4d20b89.png)

This solution has no strong coupling with any physics engine.  This solution is simple in my opinion.  This feature will allow us to store any custom meta data for each GameObject.

Thoughts? Opinions? Concerns?

**Comment by antzGames** [comment]
As long as I can get quick access to my custom data in the runtime I am happy.  I think your solution is even simpler, and allows multiple key/value pairs to be stored.

**Comment by Dgzt** [comment]
If you think this way is the winner, what I thought, I can start to implement in this weekend. @antzGames  @JamesTKhan

**Comment by JamesTKhan** [comment]
I could see some uses for this, mainly for accessing and using the data from the runtime. Storing things like, maybe an enemies starting health, damage, an NPC's name, etc.. which could vary per game object. Essentially custom properties like the Tiled example above.

**Comment by antzGames** [comment]
So the more I think about it, name/value pair custom property solution would be fantastic for many reasons on the runtime side.  Thanks for looking into this guys.
