### ISSUE TITLE
Rotated water disappear

### ISSUE THREAD

**Issue by Dgzt** [JamesTKhan/Mundus#152]
**Describe the bug**
I rotated the water because I want the wave from down to up. If I turn back with the camera the water object disappears in Editor and runtime also.

**To Reproduce**
1. Rotate the water object with -180 Y value
2. Move the water object to the 1200 X and 1200 Z value (if your terrain size is 1200)
3. Turn back with the camera
4. And the water disappear

**Screenshots**
Water transformation data:
![image](https://user-images.githubusercontent.com/1684274/233470947-c68c115a-b6a6-4e5d-9840-4af5c686f7a3.png)

Water disappear:
![water_disappear](https://user-images.githubusercontent.com/1684274/233473091-87444213-c75b-4fc4-bddf-f687e6dfcc29.gif)

**Comment by JamesTKhan** [comment]
Do you have Frustum Culling enabled? My hunch is that it is getting culled when it should not be.

**Comment by Dgzt** [comment]
> Do you have Frustum Culling enabled? My hunch is that it is getting culled when it should not be. If you have it on, can you try disabling and seeing if it still happens to confirm?

Yes, Frustum Culling is enabled. If I disabled it the water always visible.

**Comment by JamesTKhan** [comment]
Awesome thanks, that narrows it down alot.
