### ISSUE TITLE
Light component gizmo GO icon from previous projects persist when switching projects.

### ISSUE THREAD

**Issue by antzGames** [JamesTKhan/Mundus#171]
**Describe the bug**

When adding a light component to empty component in one project: if you switch to another project it still renders the light gizmo.

Restarting Mundus fixes the problem.

See screen shots below on multiple projects showing a light at x= 100, y=10,z=100 that was created on a previous project.  All I did is open a recent project.  Can someone else reproduce @Dgzt @JamesTKhan?

![image](https://github.com/JamesTKhan/Mundus/assets/10563814/c4a0f942-6ea4-436e-b6d0-00ee0dabeb0c)

![image](https://github.com/JamesTKhan/Mundus/assets/10563814/50a50aeb-a6b1-4d39-9f1b-6b4623e0be55)

![image](https://github.com/JamesTKhan/Mundus/assets/10563814/60b1fedc-10f6-4cb5-8443-6de02517be1b)

**Comment by JamesTKhan** [comment]
Yeah I can replicate it. Looks like an additional bug is that the gizmo does not come back when switching between scenes in the same project. Scene A has gizmo, Switch to Scene B, all good, switch to Scene A, gizmo not visible. 

Probably has to do with the order of the events being called in the Gizmo manager hopefully an easy fix.

**Comment by JamesTKhan** [comment]
On loading of a scene we fire off event ```ComponentAddedEvent``` which adds the gizmo to gizmo manager, but, after that event is called, a scene graph changed event is called, which the manager then clears all gizmos. Will have to refactor some things around the gizmo add/removal logic.

**Comment by antzGames** [comment]
This is a tolerable bug.  Most people starting out with Mundus just use 1 project and 1 scene, and no additional lights (other than ambient and directional light).  Maybe it can be pushed after 0.5.0 release if its a big refactor.  Your call.

**Comment by JamesTKhan** [comment]
It is a small fix, can get a PR in for it shortly
