### ISSUE TITLE
Min/Max fields for HeightMap terrain generation

### ISSUE THREAD

**Issue by JamesTKhan** [JamesTKhan/Mundus#174]
Unlike the Perlin Noise generator, there is no way to input custom min/max height values when loading a height map onto a terrain. We should look into adding min/max fields on the HeightMap tab. The height map generator code already supports a max value field and uses an hard coded value (see discussion), but may need extending to add min height.

Perlin with min/max
![image](https://github.com/JamesTKhan/Mundus/assets/28971753/24b951b7-8b93-4631-8a90-c10f3a824445)

No min/max
![image](https://github.com/JamesTKhan/Mundus/assets/28971753/745e5830-a540-4564-88ab-e335e7dc84d6)

**Comment by antzGames** [comment]
So easy to implement.  So for some reason the terrain generator always starts from height of zero and ignores the `Terraformer.heightMap(terrainComponent).minHeight()`.   I did not want to modify the terrain generator class so I just implemented a Min/Max field.  If set to negative, it inverts the heightmap, which I think is a feature.  

If min/max is blank or set to 0 (which would generate a flat terrain) then it uses +100 as the max height.

See screen shots below:

![image](https://github.com/JamesTKhan/Mundus/assets/10563814/28e95f3d-190f-4f7c-8f68-c54fc1765674)

![image](https://github.com/JamesTKhan/Mundus/assets/10563814/03f97018-9d20-4bd4-aeb9-273488834253)

@JamesTKhan if you are ok with this, I can submit a PR today.

**Comment by antzGames** [comment]
`Terraformer.heightMap(terrainComponent).minHeight()` looks like cannot be negative and it seems that the minimum is always 0.

Therefore, I have implemented a Min/Max field.  If positive then the terrain generates from 0 to max value.  If negative, then it inverts the height map.  I think of this as a feature.  If min/max value set is blank or is zero, it automatically defaults to +100.

![image](https://github.com/JamesTKhan/Mundus/assets/10563814/a6527c04-7bea-49ed-856d-9d41976673c8)

![image](https://github.com/JamesTKhan/Mundus/assets/10563814/4e037618-4ba4-4119-a14a-723eca3b68ca)

**Comment by JamesTKhan** [comment]
Resolved by https://github.com/JamesTKhan/Mundus/pull/182
