### ISSUE TITLE
Incorrect bounding box on rotated game object

### ISSUE THREAD

**Issue by Dgzt** [JamesTKhan/Mundus#222]
**Describe the bug**
The bounding boxes are not correct on rotated game objects like terrain.

**To Reproduce**
1. Rotate a game object like terrain
2. Enable bounding boxes ( Tools / Debug render options )
3. See error

**Screenshots**
![image](https://github.com/JamesTKhan/Mundus/assets/1684274/9d9204ff-50a7-4bea-885a-ce36cf57fd9e)

**Comment by freyinds** [comment]
I have a draft pull request that solves rotation but breaks scaling.
