### ISSUE TITLE
Editor to render the get forward direction of Game Object.

### ISSUE THREAD

**Issue by antzGames** [JamesTKhan/Mundus#224]
Logical next step after https://github.com/JamesTKhan/Mundus/pull/212 (Add get forward direction method )

Add a direction arrow indicator (`public Vector3 getForwardDirection(Vector3 out)` in `SimpleNode.java` in commons) to the Game Object on the editor.

Option to have this render on/off in `Tools > Debug Render Options`.  (or should it be always on?  Opinions?)

![image](https://github.com/JamesTKhan/Mundus/assets/10563814/cda9d890-67b1-494c-9ac8-981386841614)

Arrow should be red. Arrow should extend out of the GameObject's Bounding Box so user can see it clearly.

@JamesTKhan, I seem to remember a picture of your boat showing the direction arrow.  Maybe attach that image so we can visualize what is being asked here?

**Comment by freyinds** [comment]
Is your intent to have the facing arrow showing for all game objects or only the currently selected object? Or would you like to have checkboxes for both conditions?

**Comment by antzGames** [comment]
Interesting question. So usually games (at least my games) have only a few moving GameObjects and the rest are static ones.  

So my opinion is only the selected GameObject.  

Also the having the arrows show for all parent child/children node will get kinda messy, so the more I think about it, I think you should definitely show the arrow only for the selected GameObject.

**Comment by JamesTKhan** [comment]
Yes it would be a visual mess displaying for all objects at once

**Comment by freyinds** [comment]
This is working well enough to be useful now.
![2023-08-24 16_22_03-Window](https://github.com/JamesTKhan/Mundus/assets/55037409/16453e84-e9d6-48d3-a191-b19e05b93fc4)
