### ISSUE TITLE
Material > Rotate UV should be a numeric field, not slider

### ISSUE THREAD

**Issue by antzGames** [JamesTKhan/Mundus#225]
Using the `Rotate UV` slider has proved to be painful to use.  The slider units are in radians so to rotate the UV texture 90 degrees, you need to slide to exactly 1.57 (to be more precise its closer to 1.5708).

![image](https://github.com/JamesTKhan/Mundus/assets/10563814/f4ce8b4c-0f70-4be3-bbf0-dc656197ddb9)

Change the slider to a numeric field, like the Scale UV fields.

You can keep it radians, as long as you clearly specify this in the label so the user knows.  However degrees would be easier and more precise.  

![image](https://github.com/JamesTKhan/Mundus/assets/10563814/26bd4493-c5db-48c3-b100-a31bf7974b72)

**Comment by freyinds** [comment]
Next time I'll learn to link a pull request but a proposed solution is ready for review.

**Comment by antzGames** [comment]
I think you can still link this issue to your PR.  On the top right, try using:

![image](https://github.com/JamesTKhan/Mundus/assets/10563814/526d8d01-92a2-4bbe-9d71-a5065d1b0d7a)

and see if you PR is searchable.
