### ISSUE TITLE
When renaming an object, fill in current name

### ISSUE THREAD

**Issue by JamesTKhan** [JamesTKhan/Mundus#243]
**Is your feature request related to a problem? Please describe.**
When renaming an GameObject the current name is not populated.

**Describe the solution you'd like**
When renaming a GameObject it would be nice if it filled in the objects current name.

**Additional context**
![image](https://github.com/JamesTKhan/Mundus/assets/28971753/878a2502-8896-4dda-afc3-cf2cea364bdc)

**Comment by sayyidhussain** [comment]
Hello @JamesTKhan , i would like to work on this

**Comment by JamesTKhan** [comment]
> Hello @JamesTKhan , i would like to work on this

Sure, let me know if you have any questions we have also a Wiki page: https://github.com/JamesTKhan/Mundus/wiki/Working-from-source

**Comment by sayyidhussain** [comment]
just one question, in this context current name mean the name in the Inspector?
![image](https://github.com/JamesTKhan/Mundus/assets/85566851/7c7a8636-0f55-4394-abc2-2614d88853fc)

**Comment by JamesTKhan** [comment]
> just one question, in this context current name mean the name in the Inspector? ![image](https://user-images.githubusercontent.com/85566851/268220944-7c7a8636-0f55-4394-abc2-2614d88853fc.png)

Yeah, the name of the GameObject. Here is an example of how renaming works 
![ren](https://github.com/JamesTKhan/Mundus/assets/28971753/5825b59a-90b3-43b0-b2fd-11eaefbb69f4)
