### ISSUE TITLE
There already exists a texture with the same name error message but not selected texture

### ISSUE THREAD

**Issue by Dgzt** [JamesTKhan/Mundus#248]
**Describe the bug**
If import a texture and open again the texture import dialog and click to the _IMPORT_ button without select texture then the Mundus editor shows the `Error: There already exists a texture with the same name` error message.

**To Reproduce**
1. Click to the "Import" icon on toolbar and click to the "Import texture" menu item
2. Import a texture
3. Open again the "Import texture" popup (1.)
4. Click to the _IMPORT_ button without select a texture

**Screenshots**
![image](https://github.com/JamesTKhan/Mundus/assets/1684274/f0d0c9de-6568-44d2-a6f4-2397d16a9139)

**Comment by sayyidhussain** [comment]
Hello, I would like to work on this

**Comment by Dgzt** [comment]
> Hello, I would like to work on this

Sure, let me know if you have any questions.

**Comment by sayyidhussain** [comment]
create pull request #250
