### ISSUE TITLE
need javafx make the gui

### ISSUE THREAD

**Issue by qq1053831109** [JamesTKhan/Mundus#274]
need javafx make the gui. see openglfx

**Comment by Dgzt** [comment]
You mean should change the Editor's GUI framework from libGDX/VisUI to javaFX/OpenGLFX? I think it would be a very huge work and I don't see that it would be more better.

**Comment by JamesTKhan** [comment]
Thanks for the suggestion. openglfx looks interesting, but I think we are in too deep with Scene2D at this point. The amount of refactor would be too much and I don't think any one is willing spend that time on that kind of refactor even if we wanted to. Closing this issue out.
