### ISSUE TITLE
Editor crash when import texture from assets directory

### ISSUE THREAD

**Issue by schreiberdev** [JamesTKhan/Mundus#275]
**Describe the bug**
If you try to import a texture that is already placed inside the assets directory of your project the editor will crash.

**To Reproduce**
1. Copy an image into the assets directory of your project
2. Try to import it
3. The editor crashes and wont open back up
4. Manually deleting the image and the corresponding .meta file allows the editor to start again

I don't know if other kinds of assets are also affected.

**Comment by JamesTKhan** [comment]
Thanks for reporting. I thought we caught this in code but maybe not. I'm guessing it's throwing a asset already exists exception

**Comment by schreiberdev** [comment]
> I'm guessing it's throwing a asset already exists exception

I think assets that are already imported are not an issue. But when you copy a new asset into the assets folder and then try to import it things go wrong.

**Comment by JamesTKhan** [comment]
Closed, PR merged.
